---
title: "result"
output: pdf_document
date: "2024-04-07"
---
```{r}
library(ggplot2)
rep <- 500
sample_size <- c(10,50, 100, 150, 200,250)
size <- length(sample_size)
```

# null

```{r}
simulate_samples <- function(sample_size) {
  sample <- rnorm(n=sample_size)
  return(list(s=sample))
}
bfmatrix <- matrix(NA, nrow = size, ncol = rep)

for (i in 1:size) {
  for (j in 1:rep) {
    samples_result1 <- simulate_samples(sample_size[i])
    samples_result2 <- simulate_samples(sample_size[i])
    bfmatrix[i, j] <- log(pt_d_sample_test(samples_result1$s,samples_result2$s)$bf)
  }
}
row_means <- apply(bfmatrix, 1, mean)
row_means
df <- data.frame(SampleSize = sample_size, MeanRowValue = row_means)

ggplot(df, aes(x = SampleSize, y = MeanRowValue)) +
  geom_point(color = "red") +
  geom_line(color = "blue") + 
 labs(x = "Sample Size", y = "Log Bayes Factor") +
  ggtitle("Relationship between Sample Size and Log Bayes Factor")
```

# different mean

```{r}
simulate_samples <- function(sample_size, mean, variance) {
  sample <- rnorm(n=sample_size, mean = mean, sd = sqrt(variance))
  
  return(list(s=sample))
}

bfmatrix1 <- matrix(NA, nrow = size, ncol = rep)

for (i in 1:size) {
  for (j in 1:rep) {
    samples_result1 <- simulate_samples(sample_size[i], 0, 1)
    samples_result2 <- simulate_samples(sample_size[i], 100, 100)

    bfmatrix1[i, j] <- log(pt_d_sample_test(samples_result1$s,samples_result2$s)$bf)
  }
}
row_means <- apply(bfmatrix1, 1, mean)
row_means
df <- data.frame(SampleSize = sample_size, MeanRowValue = row_means)

ggplot(df, aes(x = SampleSize, y = MeanRowValue)) +
  geom_point(color = "red") +
  geom_line(color = "blue") + 
 labs(x = "Sample Size", y = "Log Bayes Factor") +
  ggtitle("Relationship between Sample Size and Log Bayes Factor")
```


# different variance

```{r}
simulate_samples <- function(sample_size, mean, variance) {
  sample <- rnorm(n=sample_size, mean = mean, sd = sqrt(variance))
  
  return(list(s=sample))
}

bfmatrix <- matrix(NA, nrow = size, ncol = rep)

for (i in 1:size) {
  for (j in 1:rep) {
    samples_result1 <- simulate_samples(sample_size[i], 0, 1)
    samples_result2 <- simulate_samples(sample_size[i], 0, 4)

    bfmatrix[i, j] <- log(pt_d_sample_test(samples_result1$s,samples_result2$s)$bf)
  }
}
row_m <- apply(bfmatrix, 1, median)
row_m

df <- data.frame(SampleSize = sample_size, MeanRowValue = row_m)

ggplot(df, aes(x = SampleSize, y = MeanRowValue)) +
  geom_point(color = "red") +
  geom_line(color = "blue") + 
 labs(x = "Sample Size", y = "Log Bayes Factor") +
  ggtitle("Relationship between Sample Size and Log Bayes Factor")
```

# Tails

```{r}
df=1
simulate_samples <- function(sample_size, mean, variance) {
  sample <- rnorm(n=sample_size, mean = mean, sd = sqrt(variance))
  
  return(list(s=sample))
}

simulate_samples2 <- function(sample_size, df) {
  sample <- rt(n = sample_size, df = df)
  return(list(s2 = sample))
}

bfmatrix <- matrix(NA, nrow = size, ncol = rep)

for (i in 1:size) {
  for (j in 1:rep) {
    samples_result1 <- simulate_samples(sample_size[i], 0, 1)
    samples_result2 <- simulate_samples2(sample_size[i], 1)

    bfmatrix[i, j] <- log(pt_d_sample_test(samples_result1$s,samples_result2$s)$bf)
  }
}
row_m <- apply(bfmatrix, 1, median)

df <- data.frame(SampleSize = sample_size, MeanRowValue = row_m)

ggplot(df, aes(x = SampleSize, y = MeanRowValue)) +
  geom_point(color = "red") +
  geom_line(color = "blue") + 
 labs(x = "Sample Size", y = "Log Bayes Factor") +
  ggtitle("Relationship between Sample Size and Log Bayes Factor")
```
